import "~/styles/globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "Web Gallery",
  description: "Generated by Justisus",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: { 
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="m-0">
        <body className={`font-sans ${geist.variable} flex flex-col gap-4 m-0`}>
          <TopNav />
          {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
